project:
  type: website
  output-dir: docs

website:
  title: "Meisam Yousefi"
  # favicon: logo.png
  twitter-card: true
  repo-url: https://github.com/MeisamYSF/MeisamYSF.github.io
  site-url: https://MeisamYSF.github.io
  navbar:
    left:
      - href: index.qmd
        text: Home
      - pub.qmd
      - cv.qmd
      
  page-footer: 
    center: "Created with Quarto -- Meisam Yousefi &copy; 2024"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    page-layout: full

editor: visual

