---
title: "Publications"
---

### Pre-prints:

*Currently N.A.*

<br />

### Research articles:

**Yousefi, M. \#**, See, W. R., Aw-Yang, K. L., Lee, W. S., Yong, C. L., Fanusi, F., Smith, G. J. D., Ooi, E. E., Li, S., Ghosh, S., and Ooi, Y. S. **\#** (2024). [GeneRaMeN enables integration, comparison, and meta-analysis of multiple ranked gene lists to identify consensus, unique, and correlated genes](https://academic.oup.com/bib/article/25/5/bbae452/7760131). *Briefings in Bioinformatics*, 25(5), bbae452.

-   Co-corresponding author

**Yousefi, M.\*,** Lee, W. S.\*, Chan, W. O. Y.\*, He, W., Mah, M. G., Yong, C. L., Deerain, J. M., Wang, L., Arcinas, C., Yan, B., Tan, D., Sia, W. R., Gamage, A. M., Yang, J., Hsu, A. C-. Y., Li, S., Linster, M., Yang, X., Ghosh, S., Anderson, D. E., Smith, G. J. D., Tan, C. W., Wang, L-. F., and Ooi, Y. S. (2023). [Betacoronaviruses SARS-CoV-2 and HCoV-OC43 infections in IGROV-1 cell line require aryl hydrocarbon receptor](https://www.tandfonline.com/doi/full/10.1080/22221751.2023.2256416). *Emerging Microbes & Infections*, 12(2), 2256416.

-   Co-first author

Cui, L., **Yousefi, M.**, Yap, X., Koh, C. W., Tay, K. S. L., Ooi, Y. S., and Chan, K. R. (2023). [Mass Spectrometry-based Lipidomics, Lipid Bioenergetics, and Web Tool for Lipid Profiling and Quantification in Human Cells](https://bio-protocol.org/en/bpdetail?id=4742&type=0). *Bio-protocol*, 13(16).

Ng, W. C., Kwek, S. S., Sun, B., **Yousefi, M.**, Ong, E. Z., Tan, H. C., Puschnik, A. S., Chan, K. R., Ooi, Y. S., and Ooi, E. E. (2022). [A fast-growing dengue virus mutant reveals a dual role of STING in response to infection](https://royalsocietypublishing.org/doi/10.1098/rsob.220227). *Open Biology*, 12220227220227.

**Yousefi, M.**, Lee, W. S., Yan, B., Cui, L., Yong, C. L., Yap, X., Tay, K. S. L., Qiao, W., Tan, D., Nurazmi, N. I., Linster, M., Lee, Y. H., Smith, G. J., Carette, J. E., Ooi, E. E., Chan, K. R. and Ooi, Y. S. (2022). [TMEM41B and VMP1 modulate cellular lipid and energy metabolism for facilitating dengue virus infection](https://journals.plos.org/plospathogens/article?id=10.1371/journal.ppat.1010763). *PLoS Pathogens*, 18(8), e1010763.

**Yousefi, M.**, Marashi, S. A., Sharifi-Zarchi, A. and Taleahmad, S., (2019). [The metabolic network model of primed/naive human embryonic stem cells underlines the importance of oxidation-reduction potential and tryptophan metabolism in primed pluripotency](https://cellandbioscience.biomedcentral.com/articles/10.1186/s13578-019-0334-7). *Cell & Bioscience*, 9(1), p.71.

Taleahmad, S., Alikhani, M., Mollamohammadi, S., **Yousefi, M.**, Taei, A., Hassani, S. N., Baharvand, H. and Salekdeh, G. H., (2019). [Inhibition of Human Y Chromosome Gene, SRY, Promotes Naive State of Human Pluripotent Stem Cells](https://pubs.acs.org/doi/10.1021/acs.jproteome.9b00396). *Journal of Proteome Research*, 18(12), pp.4254-4261.

Sababi, M., Marashi, S. A., Pourmajidian, M., Pourtabatabaei, S. S., Darki, F., Sadrzadeh, M. R., Dehghani, M., Zandieh, A., Zim, M. K., **Yousefi, M.**, Jamalkhah, M., Tabatabaei, S. K., Safaeifard, F., Talaei, A., Sobat, M., Moakedi, F., and Nejadi, P., (2017). [How accessibility influences citation counts: The case of citations to the full text articles available from ResearchGate](https://riviste.unimi.it/index.php/roars/article/view/7997). *RT. A Journal on Research Policy and Evaluation*, 5(1). (1,0) 428

<br />

### Review articles:

See, W. R., **Yousefi, M.**, and Ooi, Y. S. (2024). [A review of virus host factor discovery using CRISPR screening](https://journals.asm.org/doi/10.1128/mbio.03205-23). *mBio* 0:e03205-23.

Lee, W. S.\*, **Yousefi, M.\***, Yan, B., Yong, C. L., and Ooi, Y. S. (2021). [Know your enemy and know yourself -- the case of SARS-CoV-2 host factors](https://www.sciencedirect.com/science/article/pii/S1879625721000948). *Current Opinion in Virology*, 50, 159-170.

-   Featured on the journal cover
-   Co-first author
